version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "🔍 Debugging environment..."
      - ls -la
      - python --version
      - pip --version
      - echo "🔧 Installing dependencies directly (skipping venv)..."
      - pip install --user flask pytest
      # Install requirements if you have them
      - if [ -f requirements.txt ]; then pip install --user -r requirements.txt; fi
  
  build:
    commands:
      - echo "🧪 Running tests..."
      - python -m pytest || echo "No tests to run"
  
  post_build:
    commands:
      - echo "📦 Preparing deployment package..."
      - echo "✅ Build completed on $(date)"

artifacts:
  files:
    - app/**/*
    - deploy_todo_app.sh
    - requirements.txt
    - appspec.yml
  base-directory: '.'
