version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt

  build:
    commands:
      - echo Building the app...
      - python3 -m py_compile app/app.py

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
  discard-paths: yes
